import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import ScrollToTopOnMount from "../../template/ScrollToTopOnMount";
import { addToCart } from "../../utils/cartStorage";
import RelatedProduct from "./RelatedProduct";

const API=process.env.REACT_APP_API_URL||"http://localhost:3001/api";
const money=value=>Number(value||0).toLocaleString("vi-VN")+" ₫";

export default function ProductDetail(){
  const {slug}=useParams();const [product,setProduct]=useState(null),[related,setRelated]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[added,setAdded]=useState(false);
  useEffect(()=>{const controller=new AbortController();setLoading(true);fetch(`${API}/products/${encodeURIComponent(slug)}`,{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error("Không tìm thấy sản phẩm");return r.json()}).then(async data=>{setProduct(data);const res=await fetch(`${API}/products/recommend/${data.id}`,{signal:controller.signal});if(res.ok)setRelated(await res.json())}).catch(e=>{if(e.name!=="AbortError")setError(e.message)}).finally(()=>setLoading(false));return()=>controller.abort()},[slug]);
  const add=()=>{if(!product)return;addToCart({id:product.id,name:product.name,brand:product.brand,price:Number(product.price),quantity:1,image:product.image_url});setAdded(true);setTimeout(()=>setAdded(false),1200)};
  if(loading)return <div className="container py-5 text-center">Đang tải dữ liệu sản phẩm...</div>;
  if(error||!product)return <div className="container py-5 alert alert-danger">{error||"Sản phẩm không tồn tại"}</div>;
  return <div className="container product-detail-page mt-5 py-4 px-xl-5"><ScrollToTopOnMount/><nav className="bg-custom-light rounded mb-4"><ol className="breadcrumb p-3"><li className="breadcrumb-item"><Link to="/products">Sản phẩm</Link></li><li className="breadcrumb-item">{product.category}</li><li className="breadcrumb-item active">{product.name}</li></ol></nav><div className="row g-4 mb-5"><div className="col-lg-6"><img className="border rounded w-100 product-detail-main-image" alt={product.name} src={product.image_url}/></div><div className="col-lg-6"><span className="product-page-kicker">{product.brand}</span><h1>{product.name}</h1><h3 className="text-danger my-3">{money(product.price)}</h3><div className="mb-3"><span className="text-warning">★★★★★</span> <b>{Number(product.rating||0).toFixed(1)}</b></div><p>{product.description||"Sản phẩm chính hãng được quản lý trực tiếp từ hệ thống ElectroShop."}</p><dl className="row"><dt className="col-5">Danh mục</dt><dd className="col-7">{product.category}</dd><dt className="col-5">Bảo hành</dt><dd className="col-7">{product.warrantyMonths} tháng</dd><dt className="col-5">Tồn kho</dt><dd className="col-7">{product.stock_quantity} sản phẩm</dd></dl>{product.variants?.length>0&&<div className="mb-4"><b>Phiên bản</b><div className="d-flex flex-wrap gap-2 mt-2">{product.variants.map(v=><span className="btn btn-outline-dark btn-sm" key={v.variant_id}>{v.variant_name}</span>)}</div></div>}<div className="d-flex gap-3"><button className="btn eshop-add-cart-btn flex-fill" onClick={add}><FontAwesomeIcon icon={["fas",added?"check":"cart-plus"]}/> {added?"Đã thêm":"Thêm vào giỏ"}</button><button className="btn eshop-buy-now-btn flex-fill" onClick={add}><FontAwesomeIcon icon={["fas","bolt"]}/> Mua ngay</button></div></div></div>{product.specifications?.length>0&&<section className="mb-5"><h3>Thông số kỹ thuật</h3><div className="table-responsive"><table className="table table-striped"><tbody>{product.specifications.map(s=><tr key={s.attribute_id}><th>{s.attribute_name}</th><td>{s.attribute_value} {s.attribute_unit||""}</td></tr>)}</tbody></table></div></section>}<section><h3>Sản phẩm liên quan</h3><div className="row row-cols-1 row-cols-md-4 g-3 mt-2">{related.map(item=><RelatedProduct key={item.id} product={item}/>)}</div></section></div>;
}
