import { useCallback, useEffect, useMemo, useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { Link, Navigate } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import "./admin-enhancements.css";

const menuGroups = [
  { title:"TỔNG QUAN", items:[{label:"Dashboard",icon:"chart-pie",roles:["ADMIN","STAFF"]}]},
  { title:"QUẢN LÝ CHÍNH", items:[
    {label:"Sản phẩm",icon:"box-open",roles:["ADMIN","STAFF"]},
    {label:"Danh mục",icon:"tags",roles:["ADMIN"]},
    {label:"Nhân viên",icon:"user-tie",roles:["ADMIN"]},
    {label:"Kho & nhập xuất",icon:"warehouse",roles:["ADMIN","STAFF"]},
    {label:"Đơn hàng & trạng thái",icon:"receipt",roles:["ADMIN","STAFF"]},
  ]},
  { title:"THEO DÕI", items:[
    {label:"Báo cáo",icon:"chart-bar",roles:["ADMIN"]},
    {label:"Lịch sử hệ thống",icon:"history",roles:["ADMIN"]},
  ]},
];

const modules = {
  "Nhân viên":{resource:"staff",fields:["user_full_name","user_email","user_phone","password"],columns:[["user_id","Mã"],["user_full_name","Nhân viên"],["user_email","Email"],["products_added","Sản phẩm đã thêm"],["units_imported","Máy/hàng đã nhập"],["tasks_handled","Nghiệp vụ xử lý"],["last_activity","Hoạt động gần nhất"],["account_status","Trạng thái"]],staffActions:true},
  "Danh mục":{resource:"categories",fields:["parent_category_id","category_name","category_slug","category_description","category_status"],columns:[["category_id","Mã"],["category_name","Danh mục"],["category_slug","Đường dẫn"],["category_description","Mô tả"],["category_status","Trạng thái"]]},
  "Thương hiệu":{resource:"brands",fields:["brand_name","brand_description","brand_status"],columns:[["brand_id","Mã"],["brand_name","Thương hiệu"],["brand_description","Mô tả"],["brand_status","Trạng thái"]]},
  "Sản phẩm":{resource:"products",fields:["category_id","brand_id","product_name","sku","image_url","variant_name","variant_sku","additional_price","product_description","base_price","warranty_months","product_status"],columns:[["product_id","Mã"],["image_url","Ảnh"],["product_name","Sản phẩm"],["category_name","Danh mục"],["brand_name","Thương hiệu"],["base_price","Giá bán"],["product_status","Trạng thái"]]},
  "Đơn hàng":{resource:"orders",idKey:"order_id",fields:["order_status_id","order_note"],createDisabled:true,columns:[["order_code","Đơn hàng"],["customer_name","Khách hàng"],["order_status_name","Trạng thái"],["total_amount","Tổng tiền"],["payment_status_name","Thanh toán"],["order_created_at","Ngày tạo"]]},
  "Kho hàng":{resource:"stock",readonly:true,columns:[["product_id","Mã"],["product_name","Sản phẩm"],["current_stock","Tồn hiện tại"],["total_sold","Đã bán"],["stock_status","Cảnh báo"]]},
  "Nhập xuất kho":{resource:"inventory",fields:["product_id","variant_id","supplier_id","inventory_type_id","transaction_quantity","unit_cost","transaction_note"],columns:[["inventory_transaction_id","Mã"],["product_name","Sản phẩm"],["supplier_name","Nhà cung cấp"],["inventory_type_name","Loại"],["transaction_quantity","Số lượng"],["total_cost","Thành tiền"]]},
  "Trạng thái đơn hàng":{resource:"order-statuses",fields:["order_status_code","order_status_name"],columns:[["order_status_id","Mã"],["order_status_code","Mã hệ thống"],["order_status_name","Tên trạng thái"]]},
  "Lịch sử hệ thống":{resource:"audits",readonly:true,columns:[["audit_log_id","Mã"],["actor_user_id","Người thực hiện"],["action_name","Hành động"],["affected_table_name","Đối tượng"],["affected_record_id","Bản ghi"],["action_at","Thời gian"]]},
};

const fieldLabels={user_full_name:"Họ và tên",user_email:"Email",user_phone:"Số điện thoại",password:"Mật khẩu",parent_category_id:"Danh mục cha",category_name:"Tên danh mục",category_slug:"Đường dẫn",category_description:"Mô tả",category_status:"Trạng thái",brand_name:"Tên thương hiệu",brand_description:"Mô tả",brand_status:"Trạng thái",attribute_name:"Tên thuộc tính",spec_group:"Nhóm thông số",attribute_unit:"Đơn vị",display_order:"Thứ tự",is_highlight:"Nổi bật",category_id:"Danh mục",brand_id:"Thương hiệu",product_name:"Tên sản phẩm",product_slug:"Đường dẫn",sku:"SKU sản phẩm",image_url:"URL ảnh đại diện",variant_name:"Tên phiên bản mặc định",variant_sku:"SKU phiên bản",additional_price:"Giá cộng thêm",product_description:"Mô tả",base_price:"Giá bán",warranty_months:"Bảo hành (tháng)",product_status:"Trạng thái",order_status_id:"Trạng thái đơn",order_note:"Ghi chú",product_id:"Sản phẩm",variant_id:"Phiên bản",supplier_id:"Nhà cung cấp",inventory_type_id:"Loại giao dịch",transaction_quantity:"Số lượng",unit_cost:"Đơn giá nhập/xuất",transaction_note:"Ghi chú chứng từ",supplier_name:"Tên nhà cung cấp",supplier_phone:"Điện thoại",supplier_email:"Email",supplier_address:"Địa chỉ",supplier_status:"Trạng thái",payment_method_code:"Mã phương thức",payment_method_name:"Tên phương thức",order_status_code:"Mã trạng thái",order_status_name:"Tên trạng thái",permission_code:"Mã quyền",permission_name:"Tên quyền",permission_description:"Mô tả",config_key:"Khóa cấu hình",config_value:"Giá trị",config_description:"Mô tả",is_enabled:"Kích hoạt"};

export default function AdminDashboard(){
  const {session,logout}=useAuth(); const role=session?.user?.role;
  const [active,setActive]=useState("Dashboard"); const [collapsed,setCollapsed]=useState(false);
  const groups=useMemo(()=>menuGroups.filter(g=>!g.adminOnly||role==="ADMIN").map(g=>({...g,items:g.items.filter(i=>!i.roles||i.roles.includes(role))})),[role]);
  if(!session||!["ADMIN","STAFF"].includes(role)) return <Navigate to="/" replace/>;
  return <div className={`admin-shell ${collapsed?"sidebar-collapsed":""}`}><aside className="admin-sidebar">
    <div className="admin-brand"><span className="brand-mark"><FontAwesomeIcon icon={["fas","bolt"]}/></span><div><b>Electro<span>Admin</span></b><small>CONTROL CENTER</small></div></div>
    <button className="collapse-btn" onClick={()=>setCollapsed(!collapsed)}><FontAwesomeIcon icon={["fas",collapsed?"angle-right":"angle-left"]}/></button>
    <nav>{groups.map(group=><div className="admin-nav-group" key={group.title}><p>{group.title}</p>{group.items.map(item=><button key={item.label} className={active===item.label?"active":""} onClick={()=>setActive(item.label)} title={item.label}><FontAwesomeIcon icon={["fas",item.icon]}/><span>{item.label}</span></button>)}</div>)}</nav>
    <div className="sidebar-bottom"><div className="system-health"><i/><span><b>Hệ thống ổn định</b><small>Dữ liệu trực tiếp</small></span></div><button onClick={logout}><FontAwesomeIcon icon={["fas","sign-out-alt"]}/><span>Đăng xuất</span></button></div>
  </aside><main className="admin-main"><header className="admin-topbar"><div><p>{role==="ADMIN"?"TRANG QUẢN TRỊ":"KHU VỰC NHÂN VIÊN"}</p><h1>{active}</h1></div><div className="admin-actions"><Link to="/" className="store-link"><FontAwesomeIcon icon={["fas","arrow-left"]}/> Trở lại trang web</Link><div className="admin-profile"><span>{role==="ADMIN"?"QT":"NV"}</span><div><b>{session.user.name}</b><small>{role}</small></div></div></div></header>
    <section className="admin-content"><div className="welcome-row"><div><span className="eyebrow">ELECTROSHOP ADMIN</span><h2>{active}</h2><p>{role==="ADMIN"?"Quản lý sản phẩm, nhân viên, kho, đơn hàng và báo cáo tập trung.":"Xử lý sản phẩm, kho và đơn hàng theo công việc được giao."}</p></div></div>
      {active==="Dashboard"?<Dashboard role={role}/>:active==="Kho & nhập xuất"?<WarehouseHub/>:active==="Đơn hàng & trạng thái"?<OrderHub role={role}/>:active==="Báo cáo"?<Reports/>:<CrudModule key={active} title={active}/>} 
    </section></main></div>;
}

function Dashboard({role}){const {api}=useAuth();const [data,setData]=useState(null);useEffect(()=>{api("/management/dashboard").then(setData).catch(()=>setData({}));},[api]);if(!data)return <div className="empty-state">Đang tổng hợp dữ liệu...</div>;const cards=role==="ADMIN"?[["Doanh thu",data.revenue,"₫","Tổng tiền đã thanh toán"],["Đơn hàng",data.orders,"","Tất cả đơn hàng"],["Khách hàng mới",data.newCustomers,"","Trong 30 ngày gần nhất"],["Lợi nhuận",data.profit,"₫","Doanh thu trừ giá vốn"]]:[["Đơn hàng",data.orders,"","Đang quản lý"],["Đã nhập",data.inventory?.imported,"","Số lượng sản phẩm"],["Đã xuất",data.inventory?.exported,"","Số lượng sản phẩm"],["Sắp hết hàng",data.lowStock?.length,"","Cần xử lý sớm"]];return <><div className="metric-grid">{cards.map(([label,value,unit,note],index)=><article className="metric-card revenue animated-card" style={{animationDelay:`${index*70}ms`}} key={label}><p>{label.toUpperCase()}</p><h3>{Number(value||0).toLocaleString("vi-VN")} {unit}</h3><small>{note}</small></article>)}</div>{role==="ADMIN"&&<FinanceChart data={data}/>}<div className="dashboard-grid"><DataPanel title="Top sản phẩm" rows={data.topProducts||[]} keys={["product_name","total_sold"]}/><DataPanel title="Hàng sắp hết" rows={data.lowStock||[]} keys={["product_name","current_stock"]}/></div><DataPanel title="Đơn hàng gần đây" rows={data.recentOrders||[]} keys={["order_code","customer","total_amount","order_status_name","order_created_at"]}/></>}
function FinanceChart({data}){const money=v=>Number(v||0),revenue=money(data.revenue),profit=money(data.profit),margin=revenue?profit/revenue*100:0,bars=[["Doanh thu",revenue,"revenue"],["Giá vốn đã bán",money(data.salesCost),"cost"],["Lợi nhuận",profit,"profit"],["Giá trị kho đã nhập",money(data.importValue),"import"]],max=Math.max(...bars.map(([,v])=>v),1),days=data.dailySales||[],dailyMax=Math.max(...days.map(x=>money(x.revenue)),1),points=days.map((d,i)=>`${days.length===1?50:(i/(days.length-1))*100},${88-(money(d.revenue)/dailyMax)*72}`).join(" ");return <article className="finance-chart"><div className="finance-title"><div><span className="eyebrow">PHÂN TÍCH KINH DOANH</span><h3>Hiệu quả nhập hàng và bán ra</h3><p>So sánh dòng tiền, giá vốn và lợi nhuận thực tế</p></div><div className="finance-period"><FontAwesomeIcon icon={["far","calendar-alt"]}/> 30 ngày gần nhất</div></div><div className="finance-overview"><div className="profit-donut" style={{"--rate":`${Math.max(0,Math.min(margin,100))}%`}}><div><strong>{margin.toFixed(1)}%</strong><span>Biên lợi nhuận</span></div></div><div className="finance-bars">{bars.map(([label,value,type])=><div className="finance-row" key={label}><div><b><i className={`legend-dot ${type}`}/>{label}</b><span>{value.toLocaleString("vi-VN")} ₫</span></div><div className="bar-track"><i className={type} style={{width:`${Math.max((value/max)*100,1.5)}%`}}/></div></div>)}</div></div><div className="sales-trend"><div className="trend-head"><div><b>Xu hướng doanh thu</b><span>Doanh thu theo ngày đã thanh toán</span></div><strong>+{margin.toFixed(1)}%</strong></div>{days.length?<div className="line-chart"><div className="chart-grid"><i/><i/><i/><i/></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Biểu đồ doanh thu theo ngày"><defs><linearGradient id="salesArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7357ed" stopOpacity=".32"/><stop offset="100%" stopColor="#7357ed" stopOpacity=".02"/></linearGradient></defs><polygon points={`0,100 ${points} 100,100`} fill="url(#salesArea)"/><polyline points={points} fill="none" stroke="#6d50ea" strokeWidth="2.2" vectorEffect="non-scaling-stroke"/>{days.map((d,i)=><circle key={i} cx={days.length===1?50:(i/(days.length-1))*100} cy={88-(money(d.revenue)/dailyMax)*72} r="1.7" fill="#fff" stroke="#6d50ea" strokeWidth="1.2" vectorEffect="non-scaling-stroke"/>)}</svg><div className="chart-labels">{days.map((d,i)=><span key={i}>{new Date(d.label).toLocaleDateString("vi-VN",{day:"2-digit",month:"2-digit"})}</span>)}</div></div>:<div className="empty-state">Chưa có doanh thu theo ngày</div>}</div></article>}
function DataPanel({title,rows,keys}){return <article className="orders-card"><div className="panel-title"><h3>{title}</h3><small>{rows.length} bản ghi</small></div><div className="table-wrap"><table><tbody>{rows.map((row,i)=><tr key={i}>{keys.map(k=><td key={k}>{formatValue(row[k],k)}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="empty-state">Chưa có dữ liệu</div>}</div></article>}
function Reports(){const {api}=useAuth();const [d,setD]=useState({});useEffect(()=>{api("/management/dashboard").then(setD);},[api]);const items=[["Doanh thu",d.revenue,"credit-card"],["Tồn kho",d.lowStock?.length,"warehouse"],["Khách hàng",d.customers,"users"],["Nhập hàng",d.inventory?.imported,"download"],["Xuất hàng",d.inventory?.exported,"upload"]];return <><div className="metric-grid">{items.map(([x,v,icon],index)=><article className="metric-card animated-card" style={{animationDelay:`${index*70}ms`}} key={x}><div className="metric-head"><span><FontAwesomeIcon icon={["fas",icon]}/></span></div><p>BÁO CÁO {x.toUpperCase()}</p><h3>{Number(v||0).toLocaleString("vi-VN")}</h3><small>Cập nhật theo hoạt động hệ thống</small></article>)}</div><FinanceChart data={d}/></>}

function WarehouseHub(){const [tab,setTab]=useState("Kho hàng");const tabs=["Kho hàng","Nhập xuất kho","Nhà cung cấp","Thương hiệu"];return <div className="admin-hub"><div className="hub-tabs">{tabs.map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><CrudModule key={tab} title={tab}/></div>}
function OrderHub({role}){const [tab,setTab]=useState("Đơn hàng");const tabs=role==="ADMIN"?["Đơn hàng","Trạng thái đơn hàng"]:["Đơn hàng"];return <div className="admin-hub"><div className="hub-tabs">{tabs.map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><CrudModule key={tab} title={tab}/></div>}

function CrudModule({title}){const {api}=useAuth();const config=modules[title];const [records,setRecords]=useState([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[dialog,setDialog]=useState(null),[form,setForm]=useState({}),[toast,setToast]=useState(null);const notify=(message,type="success")=>setToast({message,type,key:Date.now()});useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(null),3600);return()=>clearTimeout(timer)},[toast]);const load=useCallback(()=>{if(!config)return;setLoading(true);api(`/management/${config.resource}?limit=100&search=${encodeURIComponent(query)}`).then(r=>setRecords(Array.isArray(r)?r:r.data||[])).catch(e=>notify(e.message,"error")).finally(()=>setLoading(false))},[api,config,query]);useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[load]);if(!config)return <div className="empty-state">Module chưa được cấu hình</div>;
  const open=(mode,row={})=>{setForm(Object.fromEntries((config.fields||[]).map(f=>[f,mode==="edit"?(row[f]??""):""])));setDialog({mode,row})};
  const recordId=row=>row[config.idKey||config.columns[0][0]];
  const save=async e=>{e.preventDefault();try{const payload={...form};if(config.resource==="products"){if(payload.image_url)payload.images=[{image_url:payload.image_url,is_thumbnail:true,sort_order:1}];if(payload.variant_name)payload.variants=[{variant_name:payload.variant_name,sku:payload.variant_sku||null,additional_price:Number(payload.additional_price||0),variant_status:"ACTIVE",is_default:true}];["image_url","variant_name","variant_sku","additional_price"].forEach(k=>delete payload[k])}const id=recordId(dialog.row);await api(dialog.mode==="create"?`/management/${config.resource}`:`/management/${config.resource}/${id}`,{method:dialog.mode==="create"?"POST":"PATCH",body:JSON.stringify(payload)});setDialog(null);notify(dialog.mode==="create"?"Thêm dữ liệu thành công":"Cập nhật dữ liệu thành công");load()}catch(e){notify(e.message,"error")}};
  const remove=async row=>{if(!window.confirm("Xóa bản ghi này?"))return;try{await api(`/management/${config.resource}/${recordId(row)}`,{method:"DELETE"});notify("Đã xóa dữ liệu thành công");load()}catch(e){notify(e.message,"error")}};
  const status=async row=>{const next=row.account_status==="ACTIVE"?"LOCKED":"ACTIVE";try{await api(`/management/staff/${row.user_id}/status`,{method:"PATCH",body:JSON.stringify({status:next})});notify(next==="LOCKED"?"Đã khóa tài khoản nhân viên":"Đã mở khóa tài khoản nhân viên");load()}catch(e){notify(e.message,"error")}};
  const reset=async row=>{const password=window.prompt(`Mật khẩu mới cho ${row.user_full_name}`);if(!password)return;try{await api(`/management/staff/${row.user_id}/reset-password`,{method:"POST",body:JSON.stringify({password})});notify("Đã đặt lại mật khẩu nhân viên") }catch(e){notify(e.message,"error")}};
  return <>{toast&&<div key={toast.key} className={`admin-toast ${toast.type}`}><span><FontAwesomeIcon icon={["fas",toast.type==="error"?"exclamation-circle":"check-circle"]}/></span><div><b>{toast.type==="error"?"Không thể thực hiện":"Thành công"}</b><p>{toast.message}</p></div><button onClick={()=>setToast(null)}>×</button></div>}{config.resource==="staff"&&<StaffSummary records={records}/>}<article className="crud-card"><div className="crud-header"><div><span className="eyebrow">QUẢN LÝ {title.toUpperCase()}</span><h2>{title}</h2><p>{loading?"Đang tải...":`${records.length} bản ghi`}</p></div><div className="crud-tools"><label className="crud-search"><FontAwesomeIcon icon={["fas","search"]}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm kiếm..."/></label>{!config.readonly&&!config.createDisabled&&<button className="crud-primary" onClick={()=>open("create")}><FontAwesomeIcon icon={["fas","plus"]}/> Thêm mới</button>}</div></div><div className="table-wrap"><table className="crud-table"><thead><tr>{config.columns.map(([,label])=><th key={label}>{label}</th>)}<th>Thao tác</th></tr></thead><tbody>{records.map(row=><tr key={recordId(row)}>{config.columns.map(([key])=><td key={key}>{formatValue(row[key],key)}</td>)}<td><div className="row-actions"><button onClick={()=>setDialog({mode:"view",row})}><FontAwesomeIcon icon={["far","eye"]}/></button>{!config.readonly&&<><button onClick={()=>open("edit",row)}><FontAwesomeIcon icon={["far","edit"]}/></button><button className="delete" onClick={()=>remove(row)}><FontAwesomeIcon icon={["far","trash-alt"]}/></button></>}{config.staffActions&&<><button title="Khóa/Mở khóa" onClick={()=>status(row)}><FontAwesomeIcon icon={["fas",row.account_status==="ACTIVE"?"lock":"unlock"]}/></button><button title="Reset mật khẩu" onClick={()=>reset(row)}><FontAwesomeIcon icon={["fas","key"]}/></button></>}</div></td></tr>)}</tbody></table>{!loading&&!records.length&&<div className="empty-state">Chưa có dữ liệu</div>}</div></article>
  {dialog&&<div className="crud-overlay" onClick={()=>setDialog(null)}><div className="crud-dialog" onClick={e=>e.stopPropagation()}><div className="dialog-head"><div><span>{dialog.mode.toUpperCase()}</span><h3>{title}</h3></div><button onClick={()=>setDialog(null)}>×</button></div>{dialog.mode==="view"?<div className="detail-list">{config.columns.map(([key,label])=><div key={key}><small>{label}</small><b>{formatValue(dialog.row[key],key)}</b></div>)}</div>:<form onSubmit={save}>{config.fields.filter(field=>!(dialog.mode==="edit"&&field==="password")).map(field=><label key={field}>{fieldLabels[field]||field}<input type={field==="password"?"password":field.includes("email")?"email":field.includes("phone")?"tel":field.includes("price")||field.includes("quantity")||field.includes("cost")||field.includes("months")?"number":"text"} min={field.includes("price")||field.includes("cost")?0:undefined} pattern={field.includes("phone")?"^(0|\\+84)[0-9]{9,10}$":undefined} minLength={field==="password"?10:undefined} title={field.includes("phone")?"Số điện thoại Việt Nam gồm 10-11 chữ số":field==="password"?"Tối thiểu 10 ký tự gồm chữ hoa, chữ thường, số và ký tự đặc biệt":undefined} required={!field.endsWith("_id")&&field!=="image_url"} value={form[field]??""} onChange={e=>setForm({...form,[field]:e.target.value})}/></label>)}<div className="dialog-actions"><button type="button" onClick={()=>setDialog(null)}>Hủy</button><button type="submit">Lưu dữ liệu</button></div></form>}</div></div>}</>}

function StaffSummary({records}){const total=(key)=>records.reduce((sum,row)=>sum+Number(row[key]||0),0),active=records.filter(row=>row.account_status==="ACTIVE").length;const items=[["Nhân viên hoạt động",active,"user-check","purple"],["Sản phẩm đã thêm",total("products_added"),"box-open","blue"],["Máy/hàng đã nhập",total("units_imported"),"truck-loading","orange"],["Nghiệp vụ đã xử lý",total("tasks_handled"),"tasks","green"]];return <div className="staff-summary">{items.map(([label,value,icon,color],index)=><article className={`staff-kpi ${color}`} style={{animationDelay:`${index*65}ms`}} key={label}><span><FontAwesomeIcon icon={["fas",icon]}/></span><div><small>{label}</small><strong>{Number(value).toLocaleString("vi-VN")}</strong></div></article>)}</div>}
function formatValue(value,key=""){if(value===null||value===undefined||value==="")return "—";if(key==="image_url")return <img className="admin-product-thumb" src={value} alt="Ảnh sản phẩm" loading="lazy"/>;if(key.includes("price")||key.includes("amount")||key.includes("cost"))return `${Number(value).toLocaleString("vi-VN")} ₫`;if(key.includes("_at")||key.includes("activity"))return new Date(value).toLocaleString("vi-VN");if(typeof value==="object")return JSON.stringify(value);return String(value)}
